"""initial schema

Revision ID: 0001_initial
Revises: None
Create Date: 2026-07-02 22:30:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Create sellers table
    op.create_table(
        'sellers',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('nickname', sa.String(length=100), nullable=False),
        sa.Column('registration_date', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    # 2. Create products table
    op.create_table(
        'products',
        sa.Column('id', sa.String(length=50), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('category_id', sa.String(length=50), nullable=False),
        sa.Column('seller_id', sa.BigInteger(), nullable=False),
        sa.Column('permalink', sa.String(length=500), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # 3. Create product_metrics_history partitioned table
    # We use raw DDL since Alembic does not natively support "PARTITION BY" syntax
    op.execute("""
        CREATE TABLE product_metrics_history (
            id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
            product_id VARCHAR(50) NOT NULL REFERENCES products(id) ON DELETE CASCADE,
            price NUMERIC(10, 2) NOT NULL,
            original_price NUMERIC(10, 2),
            available_quantity INTEGER NOT NULL,
            status VARCHAR(50) NOT NULL,
            captured_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id, captured_at)
        ) PARTITION BY RANGE (captured_at);
    """)

    # 4. Create raw_payloads partitioned table
    op.execute("""
        CREATE TABLE raw_payloads (
            id UUID NOT NULL,
            resource_type VARCHAR(50) NOT NULL,
            resource_id VARCHAR(100) NOT NULL,
            payload JSONB NOT NULL,
            captured_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id, captured_at)
        ) PARTITION BY RANGE (captured_at);
    """)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS raw_payloads;")
    op.execute("DROP TABLE IF EXISTS product_metrics_history;")
    op.drop_table('products')
    op.drop_table('sellers')
